apiVersion: batch/v1
kind: Job
metadata:
  name: init-job
  namespace: eksa-packages
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "eks-anywhere-packages.serviceAccountName" . }}
      containers:
      - name: init-cronjob
        image: {{.Values.sourceRegistry}}{{ template "template.image" .Values.cronjob }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: ECR_TOKEN_SECRET_NAME
            value: ecr-token
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: REGION
          - name: REGISTRY_MIRROR_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: registry-mirror-secret
                key: ENDPOINT
          - name: REGISTRY_MIRROR_USERNAME
            valueFrom:
              secretKeyRef:
                name: registry-mirror-secret
                key: USERNAME
          - name: REGISTRY_MIRROR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: registry-mirror-secret
                key: PASSWORD
          - name: REGISTRY_MIRROR_CACERTCONTENT
            valueFrom:
              secretKeyRef:
                name: registry-mirror-secret
                key: CACERTCONTENT
          - name: HTTP_PROXY
            value: {{ .Values.proxy.HTTP_PROXY | quote}}
          - name: HTTPS_PROXY
            value: {{ .Values.proxy.HTTPS_PROXY | quote}}
          - name: NO_PROXY
            value: {{ .Values.proxy.NO_PROXY | quote}}
